name: Build MusicPlayer APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare Android Project
        run: |
          # Create project folders
          mkdir -p MyMusicPlayer/app/src/main/java/com/example/musicplayer
          mkdir -p MyMusicPlayer/app/src/main/res/layout
          mkdir -p MyMusicPlayer/app/src/main/res/values

          # Copy Kotlin files from root (MainActivity.kt, PlayerService.kt, etc.)
          cp *.kt MyMusicPlayer/app/src/main/java/com/example/musicplayer/ || true

          # AndroidManifest.xml
          cat <<EOF > MyMusicPlayer/app/src/main/AndroidManifest.xml
             <manifest xmlns:android="http://schemas.android.com/apk/res/android">

          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
           <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>

          <application
               android:allowBackup="true"
               android:label="MusicPlayer"
              android:supportsRtl="true"
              android:theme="@style/Theme.MusicPlayer">

           <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
           </activity>

           <service
            android:name=".PlayerService"
            android:foregroundServiceType="mediaPlayback"/>
          </application>

          </manifest>
            EOF

          # Layouts
          cat <<EOF > MyMusicPlayer/app/src/main/res/layout/activity_main.xml
              <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
               android:layout_width="match_parent"
               android:layout_height="match_parent"
               android:orientation="vertical">

              <androidx.recyclerview.widget.RecyclerView
              android:id="@+id/recyclerView"
              android:layout_width="match_parent"
              android:layout_height="0dp"
               android:layout_weight="1"/>
   
              <LinearLayout
              android:id="@+id/miniPlayerContainer"
              android:layout_width="match_parent"
                android:layout_height="80dp"
                android:orientation="vertical"
               android:background="@color/black"
                android:padding="8dp"/>
            </LinearLayout>
             EOF

              cat <<EOF > MyMusicPlayer/app/src/main/res/layout/item_music.xml
              <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
             android:layout_height="wrap_content"
              android:orientation="vertical"
            android:padding="12dp">

            <TextView
                android:id="@+id/textTitle"
              android:layout_width="match_parent"
               android:layout_height="wrap_content"
               android:text="Song Title"
              android:textSize="18sp"
               android:textStyle="bold"
               android:textColor="@color/white"/>

            <TextView
                 android:id="@+id/textArtist"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                 android:text="Artist"
               android:textSize="14sp"
               android:textColor="#AAAAAA"/>
            </LinearLayout>
             EOF

          # Values
             cat <<EOF > MyMusicPlayer/app/src/main/res/values/strings.xml
                <resources>
                 <string name="app_name">MusicPlayer</string>
            </resources>
             EOF

          cat <<EOF > MyMusicPlayer/app/src/main/res/values/colors.xml
              <resources>
                <color name="black">#000000</color>
                <color name="white">#FFFFFF</color>
              </resources>
                  EOF

          cat <<EOF > MyMusicPlayer/app/src/main/res/values/themes.xml
                <resources xmlns:tools="http://schemas.android.com/tools">
                <style name="Theme.MusicPlayer" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
               <item name="colorPrimary">@color/black</item>
               <item name="colorOnPrimary">@color/white</item>
              </style>
               </resources>
               EOF

          # Settings
          cat <<EOF > MyMusicPlayer/settings.gradle
                  rootProject.name = "MyMusicPlayer"
                 include ':app'
                    EOF

          # Gradle properties
          cat <<EOF > MyMusicPlayer/gradle.properties
               android.useAndroidX=true
                 android.enableJetifier=true
                  EOF

          # Root build.gradle
          cat <<EOF > MyMusicPlayer/build.gradle
                 buildscript {
                repositories { google(); mavenCentral() }
               dependencies {
                     classpath "com.android.tools.build:gradle:8.5.0"
                        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"
              }
            }
            allprojects { repositories { google(); mavenCentral() } }
              EOF

          # App build.gradle
          cat <<EOF > MyMusicPlayer/app/build.gradle
            apply plugin: 'com.android.application'
            apply plugin: 'kotlin-android'

              android {
                namespace "com.example.musicplayer"
                compileSdk 34

                  defaultConfig {
                        applicationId "com.example.musicplayer"
                        minSdk 24
                        targetSdk 34
                         versionCode 1
                         versionName "1.0"
                     }

                  buildTypes {
                        release {
                           minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                 } 
                }
               }

              repositories {
                   google()
                      mavenCentral()
                     } 

               dependencies {
                    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.2.0"
                     implementation "androidx.core:core-ktx:1.13.1"
                      implementation "androidx.appcompat:appcompat:1.7.0"
                        implementation "com.google.android.material:material:1.12.0"
                     implementation "androidx.recyclerview:recyclerview:1.3.2"
                          implementation "androidx.media3:media3-exoplayer:1.4.1"
                       implementation "androidx.media3:media3-session:1.4.1"
                     implementation "androidx.activity:activity-ktx:1.9.2"
                      }
                  EOF

          echo "✅ Android project structure generated"

      - name: Build APK
        run: |
          cd MyMusicPlayer
          gradle assembleDebug   # use Gradle installed by setup-gradle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MusicPlayer-APK
          path: MyMusicPlayer/app/build/outputs/apk/debug/app-debug.apk
